sudo: required

services:
  - cassandra

language: go
go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
install: true

before_script:
  - go get github.com/gocql/gocql

script:
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
