sudo: required

services:
  - cassandra

language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
install: true

before_script:
  - go get github.com/gocql/gocql

script:
  - go test -coverprofile=coverage.txt -covermode=count

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
